version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mark-stopka"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - "mark-stopka"
